"""
Created on Jan 9, 2018

@author: HuyNguyen
"""

to_remove = [
    # "ppl-ref",
    # "ppl-ref_pos",
    # "ppl-ref_prod",
    # "ppl-ref_dep",
    # "ppl-prompt",
    # "ppl-prompt_pos",
    # "ppl-correct",
    # "ppl-correct_pos",
    # "ppl-correct_prod",
    # "ppl-correct_dep",
    # "ppl-ge",
    # "ppl-ge_pos",
    # "ppl-incorrect",
    # "ppl-incorrect_pos",
    # "ppl-incorrect_prod",
    # "ppl-incorrect_dep",
    # "maxsim_15_skip",
    # "maxsim_30_skip",
    # "maxsim_50_skip",
    # "maxsim_15_cbw",
    # "maxsim_30_cbw",
    # "maxsim_50_cbw",
    "lda_sim-max",
    # "lda_sim-min",
    "lda_sim-avg",
    # "ngram_match",
    # "ngram_match-lem",
    # "ngram_unseen-1",
    # "ngram_unseen-2",
    # "ngram_unseen-3",
    "error_yn",
    # "error_count",
    "error_ratio",
    # "parse_score-ratio",
    # "length_ratio",
    # "length_01",
    "length_under-min",
    "length_above-max",
    # "length_unknown",
    # "length_unknown-ratio",
    # "length_sounds",
    # "length_sounds-ratio",
    # "prompt_missing",
    # "prompt_missing-pct",
    # "prompt_DT",
    # "prompt_IN",
    # "prompt_MD",
    # "prompt_NN",
    # "prompt_VB",
    "edit_distance"
]

to_keep = [
    # "edit_pattern-CD-JJ",
    # "edit_pattern-DT-CD",
    # "edit_pattern-IN-VBP",
    # "edit_pattern-JJ-DT",
    # "edit_pattern-JJ-OO",
    # "edit_pattern-JJ-VBN",
    # "edit_pattern-LS-MD",
    # "edit_pattern-LS-OO",
    # "edit_pattern-NN-EX",
    # "edit_pattern-NN-OO",
    # "edit_pattern-NN-VB",
    # "edit_pattern-NNS-VBZ",
    # "edit_pattern-OO-LS",
    # "edit_pattern-OO-NN",
    # "edit_pattern-OO-NNP",
    # "edit_pattern-OO-PRP$",
    # "edit_pattern-OO-TO",
    # "edit_pattern-OO-VB",
    # "edit_pattern-OO-VBN",
    # "edit_pattern-OO-VBP",
    # "edit_pattern-PRP$-DT",
    # "edit_pattern-PRP$-OO",
    # "edit_pattern-RB-EX",
    # "edit_pattern-RB-JJ",
    # "edit_pattern-RB-OO",
    # "edit_pattern-VBD-VB",
    # "edit_pattern-VBN-OO",
    # "edit_pattern-VBP-FW",
    # "edit_pattern-VBP-NN",
    # "edit_pattern-VBP-OO",
    # "edit_pattern-VBZ-IN",
    # "edit_pattern-VBZ-VBP",
    # "edit_pattern-WP-WRB"
]
